const Bargardata = [
  {
    image: "/Images/51.jpeg",
    duration: "3",
    tittle: `Hank's Juiciest Beef Burger`,
    Desc: "Here's your for a crowd pleasing backyard barbecue...",
    Name: "Hank Douglas",
    time: "4 Months",
  },
  {
    image: "/Images/52.jpeg",
    duration: "5",
    tittle: "All-Americans Cheese Burger",
    Desc: "the All-American Cheeseburger has certain..",
    Name: "Kevin Francis",
    time: "2 year",
  },
  {
    image: "/Images/53.jpeg",
    duration: "4",
    tittle: "Southern Fried Chicken Burger",
    Desc: "Try our quick and easy buttermilk chicken..",
    Name: "Nicholas Denver",
    time: "8 months",
  },
  {
    image: "/Images/54.jpeg",
    duration: "4",
    tittle: "Vegan Mushroo Fried Burger",
    Desc: "Mushrooms are surprisely similae taste and texture..",
    Name: "Lily Hart",
    time: "1 year",
  },
  {
    image: "/Images/55.jpeg",
    duration: "4",
    tittle: "Helen's Healthy Beef Burger",
    Desc: "Mushrooms are surprisely similae taste and texture..",
    Name: "Walter White",
    time: "4 Months",
  },
  {
    image: "/Images/56.jpeg",
    duration: "5",
    tittle: "Ultimate Double-Decker Burger",
    Desc: "Here's your for a crowd pleasing backyard barbecue",
    Name: "Jessy pinkman",
    time: "2 year",
  },
  {
    image: "/Images/57.jpeg",
    duration: "1",
    tittle: "Homemade Cheese Burger",
    Desc: "Here's your for a crowd pleasing backyard barbecue",
    Name: "Skyler",
    time: "8 months",
  },
  {
    image: "/Images/58.jpeg",
    duration: "2",
    tittle: "Green Tomoto Fried Burger",
    Desc: "Here's your for a crowd pleasing backyard barbecue",
    Name: "Hank Douglas",
    time: "1 year",
  },
];
export default Bargardata;
